/**
 * Tenant-scoped Client Portal services and requests.
 *
 * The unfinished upstream portal drafts use incompatible identity and bearer-token
 * tables. This migration extends the controlled `portal_*` model introduced by
 * 2026072100200_client_portal_collaboration instead.
 */
exports.up = (pgm) => {
  pgm.sql(`
    CREATE TABLE IF NOT EXISTS portal_services (
      id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
      created_by UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
      name TEXT NOT NULL,
      description TEXT,
      service_key TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'draft',
      service_data JSONB NOT NULL DEFAULT '{}'::JSONB,
      is_public BOOLEAN NOT NULL DEFAULT FALSE,
      price NUMERIC(12,2),
      currency CHAR(3) NOT NULL DEFAULT 'USD',
      category TEXT,
      cover_image_key TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT portal_services_name_check
        CHECK (char_length(name) BETWEEN 1 AND 120),
      CONSTRAINT portal_services_key_check
        CHECK (service_key ~ '^[A-Z0-9]{2,8}$'),
      CONSTRAINT portal_services_status_check
        CHECK (status IN ('active', 'inactive', 'draft')),
      CONSTRAINT portal_services_price_check
        CHECK (price IS NULL OR price >= 0),
      CONSTRAINT portal_services_currency_check
        CHECK (currency ~ '^[A-Z]{3}$'),
      CONSTRAINT portal_services_scope_unique UNIQUE (id, team_id),
      CONSTRAINT portal_services_team_key_unique UNIQUE (team_id, service_key)
    );

    CREATE TABLE IF NOT EXISTS portal_service_clients (
      service_id UUID NOT NULL,
      team_id UUID NOT NULL,
      client_id UUID NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      PRIMARY KEY (service_id, client_id),
      CONSTRAINT portal_service_clients_service_scope_fk
        FOREIGN KEY (service_id, team_id)
        REFERENCES portal_services(id, team_id) ON DELETE CASCADE,
      CONSTRAINT portal_service_clients_client_scope_fk
        FOREIGN KEY (client_id, team_id)
        REFERENCES clients(id, team_id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS portal_requests (
      id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      request_number BIGINT GENERATED BY DEFAULT AS IDENTITY,
      request_no TEXT NOT NULL,
      team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
      client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
      service_id UUID NOT NULL REFERENCES portal_services(id) ON DELETE RESTRICT,
      submitted_by_membership_id UUID REFERENCES portal_client_memberships(id)
        ON DELETE SET NULL,
      assigned_to UUID REFERENCES users(id) ON DELETE SET NULL,
      status TEXT NOT NULL DEFAULT 'pending',
      request_data JSONB NOT NULL DEFAULT '{}'::JSONB,
      notes TEXT,
      accepted_at TIMESTAMPTZ,
      completed_at TIMESTAMPTZ,
      rejected_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT portal_requests_status_check CHECK (
        status IN (
          'pending',
          'accepted',
          'in_progress',
          'waiting_on_client',
          'completed',
          'rejected',
          'cancelled'
        )
      ),
      CONSTRAINT portal_requests_notes_check
        CHECK (notes IS NULL OR char_length(notes) <= 10000),
      CONSTRAINT portal_requests_scope_unique UNIQUE (id, team_id, client_id),
      CONSTRAINT portal_requests_team_number_unique UNIQUE (team_id, request_no),
      CONSTRAINT portal_requests_service_scope_fk
        FOREIGN KEY (service_id, team_id)
        REFERENCES portal_services(id, team_id) ON DELETE RESTRICT,
      CONSTRAINT portal_requests_client_scope_fk
        FOREIGN KEY (client_id, team_id)
        REFERENCES clients(id, team_id) ON DELETE CASCADE,
      CONSTRAINT portal_requests_membership_scope_fk
        FOREIGN KEY (submitted_by_membership_id, team_id, client_id)
        REFERENCES portal_client_memberships(id, team_id, client_id)
    );

    CREATE TABLE IF NOT EXISTS portal_request_status_history (
      id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      request_id UUID NOT NULL,
      team_id UUID NOT NULL,
      client_id UUID NOT NULL,
      from_status TEXT,
      to_status TEXT NOT NULL,
      changed_by_membership_id UUID REFERENCES portal_client_memberships(id)
        ON DELETE RESTRICT,
      changed_by_staff_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
      notes TEXT,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT portal_request_history_actor_check CHECK (
        (changed_by_membership_id IS NOT NULL AND changed_by_staff_user_id IS NULL)
        OR (changed_by_membership_id IS NULL AND changed_by_staff_user_id IS NOT NULL)
      ),
      CONSTRAINT portal_request_history_request_scope_fk
        FOREIGN KEY (request_id, team_id, client_id)
        REFERENCES portal_requests(id, team_id, client_id) ON DELETE CASCADE,
      CONSTRAINT portal_request_history_membership_scope_fk
        FOREIGN KEY (changed_by_membership_id, team_id, client_id)
        REFERENCES portal_client_memberships(id, team_id, client_id)
    );

    CREATE TABLE IF NOT EXISTS portal_request_comments (
      id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      request_id UUID NOT NULL,
      team_id UUID NOT NULL,
      client_id UUID NOT NULL,
      membership_id UUID REFERENCES portal_client_memberships(id) ON DELETE RESTRICT,
      staff_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
      sender_type TEXT NOT NULL,
      sender_name TEXT NOT NULL,
      comment TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT portal_request_comments_sender_check
        CHECK (sender_type IN ('client', 'staff')),
      CONSTRAINT portal_request_comments_actor_check CHECK (
        (sender_type = 'client' AND membership_id IS NOT NULL AND staff_user_id IS NULL)
        OR (sender_type = 'staff' AND membership_id IS NULL AND staff_user_id IS NOT NULL)
      ),
      CONSTRAINT portal_request_comments_length_check
        CHECK (char_length(comment) BETWEEN 1 AND 5000),
      CONSTRAINT portal_request_comments_request_scope_fk
        FOREIGN KEY (request_id, team_id, client_id)
        REFERENCES portal_requests(id, team_id, client_id) ON DELETE CASCADE,
      CONSTRAINT portal_request_comments_membership_scope_fk
        FOREIGN KEY (membership_id, team_id, client_id)
        REFERENCES portal_client_memberships(id, team_id, client_id)
    );

    CREATE TABLE IF NOT EXISTS portal_request_attachments (
      id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      request_id UUID NOT NULL,
      team_id UUID NOT NULL,
      client_id UUID NOT NULL,
      membership_id UUID REFERENCES portal_client_memberships(id) ON DELETE RESTRICT,
      staff_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
      sender_type TEXT NOT NULL,
      object_key TEXT NOT NULL,
      file_name TEXT NOT NULL,
      mime_type TEXT NOT NULL,
      size BIGINT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT portal_request_attachments_sender_check
        CHECK (sender_type IN ('client', 'staff')),
      CONSTRAINT portal_request_attachments_actor_check CHECK (
        (sender_type = 'client' AND membership_id IS NOT NULL AND staff_user_id IS NULL)
        OR (sender_type = 'staff' AND membership_id IS NULL AND staff_user_id IS NOT NULL)
      ),
      CONSTRAINT portal_request_attachments_file_name_check
        CHECK (char_length(file_name) BETWEEN 1 AND 255),
      CONSTRAINT portal_request_attachments_size_check
        CHECK (size > 0),
      CONSTRAINT portal_request_attachments_request_scope_fk
        FOREIGN KEY (request_id, team_id, client_id)
        REFERENCES portal_requests(id, team_id, client_id) ON DELETE CASCADE,
      CONSTRAINT portal_request_attachments_membership_scope_fk
        FOREIGN KEY (membership_id, team_id, client_id)
        REFERENCES portal_client_memberships(id, team_id, client_id)
    );

    CREATE INDEX IF NOT EXISTS idx_portal_services_team_status
      ON portal_services(team_id, status, updated_at DESC);
    CREATE INDEX IF NOT EXISTS idx_portal_services_public
      ON portal_services(team_id, is_public, status);
    CREATE INDEX IF NOT EXISTS idx_portal_service_clients_scope
      ON portal_service_clients(team_id, client_id, service_id);
    CREATE INDEX IF NOT EXISTS idx_portal_requests_scope_created
      ON portal_requests(team_id, client_id, created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_portal_requests_team_status
      ON portal_requests(team_id, status, updated_at DESC);
    CREATE INDEX IF NOT EXISTS idx_portal_requests_service
      ON portal_requests(service_id, created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_portal_requests_assignee
      ON portal_requests(team_id, assigned_to, status);
    CREATE INDEX IF NOT EXISTS idx_portal_request_history_scope
      ON portal_request_status_history(team_id, client_id, request_id, created_at);
    CREATE INDEX IF NOT EXISTS idx_portal_request_comments_scope
      ON portal_request_comments(team_id, client_id, request_id, created_at);
    CREATE INDEX IF NOT EXISTS idx_portal_request_attachments_scope
      ON portal_request_attachments(team_id, client_id, request_id, created_at);

    COMMENT ON TABLE portal_services IS
      'Tenant-scoped services and customizable request-form definitions.';
    COMMENT ON TABLE portal_requests IS
      'Client requests scoped through the separate portal membership audience.';
    COMMENT ON COLUMN portal_request_attachments.object_key IS
      'Private object-storage key. Never expose directly to clients.';
  `);
};

exports.down = () => {
  // Services, request history, comments, and attachment metadata are preserved.
};
