/**
 * Tenant-scoped Client Portal invoices, payment attempts, manual evidence, and
 * idempotent provider webhook receipts.
 *
 * The old public portal draft used globally unique invoice numbers and weak
 * client references. This controlled chain keeps every financial row bound to
 * one team/client scope and stores no card data.
 */
exports.up = (pgm) => {
  pgm.sql(`
    CREATE TABLE IF NOT EXISTS portal_invoices (
      id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      invoice_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY,
      invoice_no TEXT NOT NULL,
      team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
      client_id UUID NOT NULL,
      request_id UUID,
      created_by_user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
      status TEXT NOT NULL DEFAULT 'draft',
      currency CHAR(3) NOT NULL DEFAULT 'USD',
      subtotal NUMERIC(14,2) NOT NULL DEFAULT 0,
      discount_type TEXT NOT NULL DEFAULT 'none',
      discount_value NUMERIC(14,4) NOT NULL DEFAULT 0,
      discount_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
      tax_rate NUMERIC(7,4) NOT NULL DEFAULT 0,
      tax_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
      amount NUMERIC(14,2) NOT NULL DEFAULT 0,
      due_date DATE,
      notes TEXT,
      sent_at TIMESTAMPTZ,
      paid_at TIMESTAMPTZ,
      cancelled_at TIMESTAMPTZ,
      version INTEGER NOT NULL DEFAULT 1,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT portal_invoices_status_check CHECK (
        status IN (
          'draft',
          'sent',
          'payment_pending',
          'paid',
          'overdue',
          'cancelled'
        )
      ),
      CONSTRAINT portal_invoices_currency_check CHECK (
        currency ~ '^[A-Z]{3}$'
      ),
      CONSTRAINT portal_invoices_discount_type_check CHECK (
        discount_type IN ('none', 'percentage', 'fixed')
      ),
      CONSTRAINT portal_invoices_amounts_check CHECK (
        subtotal >= 0
        AND discount_value >= 0
        AND discount_amount >= 0
        AND discount_amount <= subtotal
        AND tax_rate >= 0
        AND tax_rate <= 100
        AND tax_amount >= 0
        AND amount >= 0
        AND amount = round(subtotal - discount_amount + tax_amount, 2)
      ),
      CONSTRAINT portal_invoices_notes_check CHECK (
        notes IS NULL OR char_length(notes) <= 10000
      ),
      CONSTRAINT portal_invoices_scope_unique UNIQUE (id, team_id, client_id),
      CONSTRAINT portal_invoices_team_number_unique UNIQUE (team_id, invoice_no),
      CONSTRAINT portal_invoices_client_scope_fk
        FOREIGN KEY (client_id, team_id)
        REFERENCES clients(id, team_id) ON DELETE CASCADE,
      CONSTRAINT portal_invoices_request_scope_fk
        FOREIGN KEY (request_id, team_id, client_id)
        REFERENCES portal_requests(id, team_id, client_id) ON DELETE RESTRICT
    );

    CREATE TABLE IF NOT EXISTS portal_invoice_items (
      id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      invoice_id UUID NOT NULL,
      team_id UUID NOT NULL,
      client_id UUID NOT NULL,
      position INTEGER NOT NULL,
      description TEXT NOT NULL,
      quantity NUMERIC(12,3) NOT NULL,
      unit_amount NUMERIC(14,2) NOT NULL,
      line_amount NUMERIC(14,2) NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT portal_invoice_items_description_check CHECK (
        char_length(description) BETWEEN 1 AND 500
      ),
      CONSTRAINT portal_invoice_items_amount_check CHECK (
        quantity > 0
        AND unit_amount >= 0
        AND line_amount = round(quantity * unit_amount, 2)
      ),
      CONSTRAINT portal_invoice_items_position_unique
        UNIQUE (invoice_id, position),
      CONSTRAINT portal_invoice_items_scope_fk
        FOREIGN KEY (invoice_id, team_id, client_id)
        REFERENCES portal_invoices(id, team_id, client_id) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS portal_payment_settings (
      team_id UUID PRIMARY KEY REFERENCES teams(id) ON DELETE CASCADE,
      manual_enabled BOOLEAN NOT NULL DEFAULT FALSE,
      manual_instructions TEXT,
      stripe_enabled BOOLEAN NOT NULL DEFAULT FALSE,
      default_payment_terms_days INTEGER NOT NULL DEFAULT 14,
      updated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT portal_payment_settings_terms_check CHECK (
        default_payment_terms_days BETWEEN 0 AND 365
      ),
      CONSTRAINT portal_payment_settings_instructions_check CHECK (
        manual_instructions IS NULL
        OR char_length(manual_instructions) <= 5000
      )
    );

    CREATE TABLE IF NOT EXISTS portal_invoice_payments (
      id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      invoice_id UUID NOT NULL,
      team_id UUID NOT NULL,
      client_id UUID NOT NULL,
      submitted_by_membership_id UUID,
      submitted_by_name TEXT,
      submitted_by_email TEXT,
      provider TEXT NOT NULL,
      status TEXT NOT NULL,
      amount NUMERIC(14,2) NOT NULL,
      currency CHAR(3) NOT NULL,
      idempotency_key TEXT NOT NULL,
      checkout_session_id TEXT,
      payment_intent_id TEXT,
      provider_reference TEXT,
      failure_code TEXT,
      failure_message TEXT,
      refunded_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
      succeeded_at TIMESTAMPTZ,
      failed_at TIMESTAMPTZ,
      refunded_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT portal_invoice_payments_provider_check CHECK (
        provider IN ('stripe', 'manual')
      ),
      CONSTRAINT portal_invoice_payments_status_check CHECK (
        status IN (
          'checkout_pending',
          'pending_review',
          'processing',
          'succeeded',
          'failed',
          'refunded',
          'cancelled'
        )
      ),
      CONSTRAINT portal_invoice_payments_amount_check CHECK (amount > 0),
      CONSTRAINT portal_invoice_payments_refund_check CHECK (
        refunded_amount >= 0 AND refunded_amount <= amount
      ),
      CONSTRAINT portal_invoice_payments_currency_check CHECK (
        currency ~ '^[A-Z]{3}$'
      ),
      CONSTRAINT portal_invoice_payments_failure_check CHECK (
        failure_message IS NULL OR char_length(failure_message) <= 1000
      ),
      CONSTRAINT portal_invoice_payments_scope_unique
        UNIQUE (id, invoice_id, team_id, client_id),
      CONSTRAINT portal_invoice_payments_idempotency_unique
        UNIQUE (team_id, idempotency_key),
      CONSTRAINT portal_invoice_payments_invoice_scope_fk
        FOREIGN KEY (invoice_id, team_id, client_id)
        REFERENCES portal_invoices(id, team_id, client_id) ON DELETE RESTRICT
    );

    CREATE UNIQUE INDEX IF NOT EXISTS idx_portal_invoice_payments_checkout
      ON portal_invoice_payments(checkout_session_id)
      WHERE checkout_session_id IS NOT NULL;
    CREATE UNIQUE INDEX IF NOT EXISTS idx_portal_invoice_payments_intent
      ON portal_invoice_payments(payment_intent_id)
      WHERE payment_intent_id IS NOT NULL;
    CREATE UNIQUE INDEX IF NOT EXISTS idx_portal_invoice_payments_one_active
      ON portal_invoice_payments(invoice_id, team_id, client_id)
      WHERE status IN (
        'checkout_pending',
        'pending_review',
        'processing',
        'succeeded'
      );

    CREATE TABLE IF NOT EXISTS portal_payment_evidence (
      id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      payment_id UUID NOT NULL,
      invoice_id UUID NOT NULL,
      team_id UUID NOT NULL,
      client_id UUID NOT NULL,
      submitted_by_membership_id UUID NOT NULL,
      object_key TEXT NOT NULL,
      file_name TEXT NOT NULL,
      mime_type TEXT NOT NULL,
      size BIGINT NOT NULL,
      status TEXT NOT NULL DEFAULT 'submitted',
      review_note TEXT,
      reviewed_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
      reviewed_at TIMESTAMPTZ,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT portal_payment_evidence_status_check CHECK (
        status IN ('submitted', 'accepted', 'rejected')
      ),
      CONSTRAINT portal_payment_evidence_file_check CHECK (
        size > 0 AND char_length(file_name) BETWEEN 1 AND 255
      ),
      CONSTRAINT portal_payment_evidence_note_check CHECK (
        review_note IS NULL OR char_length(review_note) <= 2000
      ),
      CONSTRAINT portal_payment_evidence_payment_scope_fk
        FOREIGN KEY (payment_id, invoice_id, team_id, client_id)
        REFERENCES portal_invoice_payments(
          id, invoice_id, team_id, client_id
        ) ON DELETE CASCADE
    );

    CREATE TABLE IF NOT EXISTS portal_payment_webhook_events (
      id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
      provider TEXT NOT NULL,
      provider_event_id TEXT NOT NULL,
      event_type TEXT NOT NULL,
      provider_object_id TEXT,
      payload_sha256 TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'processing',
      attempt_count INTEGER NOT NULL DEFAULT 1,
      error_message TEXT,
      received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      processed_at TIMESTAMPTZ,
      updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
      CONSTRAINT portal_payment_webhook_provider_check CHECK (
        provider IN ('stripe')
      ),
      CONSTRAINT portal_payment_webhook_status_check CHECK (
        status IN ('processing', 'processed', 'ignored', 'failed')
      ),
      CONSTRAINT portal_payment_webhook_hash_check CHECK (
        payload_sha256 ~ '^[0-9a-f]{64}$'
      ),
      CONSTRAINT portal_payment_webhook_event_unique
        UNIQUE (provider, provider_event_id)
    );

    ALTER TABLE user_notifications
      ADD COLUMN IF NOT EXISTS portal_invoice_id UUID;

    DO $$
    BEGIN
      ALTER TABLE user_notifications
        ADD CONSTRAINT user_notifications_portal_invoice_id_fk
        FOREIGN KEY (portal_invoice_id)
        REFERENCES portal_invoices(id) ON DELETE CASCADE;
    EXCEPTION
      WHEN duplicate_object THEN NULL;
    END
    $$;

    ALTER TABLE portal_notifications
      ALTER COLUMN request_id DROP NOT NULL,
      ADD COLUMN IF NOT EXISTS invoice_id UUID;

    ALTER TABLE portal_notifications
      DROP CONSTRAINT IF EXISTS portal_notifications_event_type_check;
    ALTER TABLE portal_notifications
      DROP CONSTRAINT IF EXISTS portal_notifications_reference_check;

    ALTER TABLE portal_notifications
      ADD CONSTRAINT portal_notifications_event_type_check CHECK (
        event_type IN (
          'request_created',
          'request_status_updated',
          'request_assigned',
          'request_comment_added',
          'request_attachment_added',
          'invoice_sent',
          'invoice_payment_pending',
          'invoice_paid',
          'invoice_payment_failed',
          'invoice_refunded'
        )
      ),
      ADD CONSTRAINT portal_notifications_reference_check CHECK (
        (request_id IS NOT NULL AND invoice_id IS NULL)
        OR (request_id IS NULL AND invoice_id IS NOT NULL)
      );

    DO $$
    BEGIN
      ALTER TABLE portal_notifications
        ADD CONSTRAINT portal_notifications_invoice_scope_fk
        FOREIGN KEY (invoice_id, team_id, client_id)
        REFERENCES portal_invoices(id, team_id, client_id)
        ON DELETE CASCADE;
    EXCEPTION
      WHEN duplicate_object THEN NULL;
    END
    $$;

    CREATE INDEX IF NOT EXISTS idx_portal_invoices_team_status
      ON portal_invoices(team_id, status, updated_at DESC);
    CREATE INDEX IF NOT EXISTS idx_portal_invoices_client_created
      ON portal_invoices(team_id, client_id, created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_portal_invoices_request
      ON portal_invoices(request_id, created_at DESC)
      WHERE request_id IS NOT NULL;
    CREATE INDEX IF NOT EXISTS idx_portal_invoice_items_invoice
      ON portal_invoice_items(invoice_id, position);
    CREATE INDEX IF NOT EXISTS idx_portal_invoice_payments_invoice
      ON portal_invoice_payments(invoice_id, created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_portal_payment_evidence_scope
      ON portal_payment_evidence(team_id, client_id, invoice_id, created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_portal_payment_webhook_status
      ON portal_payment_webhook_events(status, received_at);
    CREATE INDEX IF NOT EXISTS idx_user_notifications_portal_invoice
      ON user_notifications(user_id, portal_invoice_id, created_at DESC)
      WHERE portal_invoice_id IS NOT NULL;
    CREATE INDEX IF NOT EXISTS idx_portal_notifications_invoice
      ON portal_notifications(invoice_id, created_at DESC)
      WHERE invoice_id IS NOT NULL;

    COMMENT ON TABLE portal_invoices IS
      'Tenant-scoped client invoices. Totals are calculated server-side.';
    COMMENT ON TABLE portal_invoice_payments IS
      'Payment attempts and reconciliation state. No card data is stored.';
    COMMENT ON TABLE portal_payment_webhook_events IS
      'Idempotent signed-provider receipts without raw payment payloads.';
  `);
};

exports.down = () => {
  // Financial history and provider reconciliation receipts are intentionally preserved.
};
